import type { MethodId } from '../types';

export const bundledBenchmarkMethodIds: MethodId[] = [
  'topsis',
  'ahp',
  'dematel',
  'vikor',
  'copras',
  'saw',
  'srp',
  'fuca',
  'seca',
  'dear',
  'eamr',
  'rawec',
  'comet',
  'wpm',
  'waspas',
  'moora',
  'moosra',
  'arlon',
  'macont',
  'aras',
  'mabac',
  'codas',
  'cocoso',
  'mairca',
  'edas',
  'gra',
  'grp',
  'ram',
  'cradis',
  'mara',
  'raps',
  'oreste',
  'qualiflex',
  'regime',
  'evamix',
  'lexicographic',
  'marcos',
  'smart',
  'maut',
  'smarter',
  'macbeth',
  'pugh',
  'ocra',
  'psi',
  'piv',
  'rov',
  'wisp',
  'todim',
  'spotis',
  'espSpotis',
  'balancedSpotis',
  'wedba',
  'lmaw',
  'dnma',
  'probid',
  'sprobid',
  'rim',
  'rafsi',
  'lopm',
  'aroman',
  'cobra',
  'ervd',
  'promethee',
  'electre',
  'multimoora',
];

export function hasBundledBenchmark(methodId: MethodId): boolean {
  return bundledBenchmarkMethodIds.includes(methodId);
}

export function benchmarkCoverageLabel(methodId: MethodId): string {
  return hasBundledBenchmark(methodId)
    ? 'This method has built-in benchmark checks'
    : 'This method runs internal checks, but still needs a published benchmark before certification';
}
