import type { MethodId } from '../types';

export const methodPurpose: Record<MethodId, string> = {
  topsis: 'Best when you want the option closest to your ideal result and farthest from the worst result.',
  ahp: 'Best when people compare options two at a time instead of filling a score table.',
  dematel: 'Best when you want to see which factors influence other factors.',
  vikor: 'Best when you need a balanced compromise, not just the highest raw score.',
  copras: 'Best when you want a clear proportional score for each option.',
  saw: 'A simple weighted scorecard: multiply each criterion by its weight and add the results.',
  srp: 'Ranks each option criterion by criterion, then combines those ranks.',
  fuca: 'Uses criterion-by-criterion ranks when raw values are hard to compare directly.',
  seca: 'Chooses both criterion weights and option scores from the data.',
  dear: 'Useful for performance studies where the data should shape the importance of each criterion.',
  eamr: 'Balances benefit and cost criteria with a compact final score.',
  rawec: 'Uses two rounds of scaling to compare options with less sensitivity to raw units.',
  comet: 'Builds a preference model from reference points, then scores your real options.',
  wpm: 'A weighted product scorecard: useful when criteria should multiply rather than add.',
  waspas: 'Blends a simple scorecard with a weighted product model.',
  moora: 'Compares options by separating helpful criteria from costly criteria.',
  moosra: 'Compares the total helpful score against the total costly score.',
  arlon: 'Uses logarithmic scaling when differences between values should be softened.',
  macont: 'Combines several scaled views of the same decision into one ranking.',
  aras: 'Scores each option against an ideal reference option.',
  edas: 'Ranks options by how far they sit above or below the average option.',
  mabac: 'Ranks options by their distance from a neutral boundary line.',
  codas: 'Ranks options by their distance from the worst reference point.',
  cocoso: 'Combines several scoring styles to produce a compromise ranking.',
  cradis: 'Ranks options by how they deviate from ideal and worst reference points.',
  mara: 'Compares each option with the strongest option across the decision space.',
  raps: 'Compares options by their geometric similarity to an ideal option.',
  oreste: 'Useful when both criterion order and option order matter.',
  qualiflex: 'Tests possible ranking orders and picks the most consistent one.',
  regime: 'Compares options pair by pair and counts weighted wins.',
  evamix: 'Useful when your decision mixes numeric ratings and ordered categories.',
  lexicographic: 'Uses your criterion priority order strictly: the first decisive criterion wins.',
  marcos: 'Scores options against ideal and worst reference options.',
  mairca: 'Ranks options by the gap between expected and actual performance.',
  promethee: 'Compares options pair by pair and shows positive and negative preference flow.',
  electre: 'Useful when you need outranking logic and threshold-based comparisons.',
  smart: 'A straightforward weighted utility scorecard.',
  maut: 'Combines individual utility scores into one overall utility score.',
  smarter: 'Uses your criterion order to create weights, then builds a utility score.',
  macbeth: 'Turns qualitative attractiveness judgments into numeric value scores.',
  pugh: 'Compares every option against a baseline option.',
  ocra: 'Ranks options by operational competitiveness across benefit and cost criteria.',
  multimoora: 'Combines several MOORA views for a more robust ranking.',
  psi: 'Creates weights from the spread in your criteria, then ranks options.',
  piv: 'Ranks options by their weighted proximity values.',
  rov: 'Compares best-case and worst-case utility for each option.',
  wisp: 'Combines weighted sum and product score components.',
  todim: 'Uses gain-loss dominance, useful when relative advantage matters.',
  ram: 'Builds a root assessment score from benefit and cost criteria.',
  gra: 'Ranks options by grey relational similarity.',
  grp: 'Ranks options by projection toward good and bad reference points.',
  spotis: 'Ranks options by distance from a stable ideal point.',
  espSpotis: 'Ranks options by distance from an expected target point you define.',
  balancedSpotis: 'Balances distance from the ideal point and your expected target point.',
  wedba: 'Ranks options by weighted distance to ideal and worst points.',
  lmaw: 'Uses logarithmic scaling before creating a final weighted score.',
  dnma: 'Combines multiple normalized views into one ranking.',
  probid: 'Ranks options using ideal, average, and worst distance signals.',
  sprobid: 'A simpler PROBID-style ranking using grouped ideal-distance signals.',
  rim: 'Ranks options by closeness to an ideal interval.',
  rafsi: 'Maps different criteria into a shared decision scale before ranking.',
  lopm: 'Useful when criteria have lower, upper, or target limits.',
  aroman: 'Combines ratio analysis and blended scaling into one ranking.',
  cobra: 'Ranks options by distance from ideal, average, and worst reference points.',
  ervd: 'Ranks options by distance from a reference point chosen by the decision maker.',
};

export const methodFamilies = {
  all: 'All methods',
  utility: 'Simple scorecards',
  distance: 'Ideal or target based',
  compromise: 'Balanced compromise',
  ratio: 'Proportional scoring',
  outranking: 'Pair-by-pair comparison',
  causal: 'Factor influence',
  pairwise: 'Pairwise priority',
  grey: 'Grey relational',
  newer: 'Advanced ranking',
} as const;

export type MethodFamily = keyof typeof methodFamilies;

export const methodFamilyById: Record<MethodId, Exclude<MethodFamily, 'all'>> = {
  topsis: 'distance',
  ahp: 'pairwise',
  dematel: 'causal',
  vikor: 'compromise',
  copras: 'ratio',
  saw: 'utility',
  srp: 'newer',
  fuca: 'newer',
  seca: 'newer',
  dear: 'newer',
  eamr: 'newer',
  rawec: 'newer',
  comet: 'newer',
  wpm: 'utility',
  waspas: 'utility',
  moora: 'ratio',
  moosra: 'ratio',
  arlon: 'newer',
  macont: 'newer',
  aras: 'ratio',
  edas: 'distance',
  mabac: 'distance',
  codas: 'distance',
  cocoso: 'compromise',
  cradis: 'distance',
  mara: 'newer',
  raps: 'newer',
  oreste: 'compromise',
  qualiflex: 'compromise',
  regime: 'compromise',
  evamix: 'compromise',
  lexicographic: 'compromise',
  marcos: 'ratio',
  mairca: 'ratio',
  promethee: 'outranking',
  electre: 'outranking',
  smart: 'utility',
  maut: 'utility',
  smarter: 'utility',
  macbeth: 'utility',
  pugh: 'utility',
  ocra: 'newer',
  multimoora: 'compromise',
  psi: 'newer',
  piv: 'distance',
  rov: 'utility',
  wisp: 'utility',
  todim: 'newer',
  ram: 'utility',
  gra: 'grey',
  grp: 'grey',
  spotis: 'distance',
  espSpotis: 'distance',
  balancedSpotis: 'distance',
  wedba: 'distance',
  lmaw: 'utility',
  dnma: 'compromise',
  probid: 'distance',
  sprobid: 'distance',
  rim: 'distance',
  rafsi: 'newer',
  lopm: 'distance',
  aroman: 'utility',
  cobra: 'distance',
  ervd: 'distance',
};
