import type { MethodId } from '../types';

export const methodPurpose: Record<MethodId, string> = {
  topsis: 'Rank alternatives by distance from ideal solution.',
  ahp: 'Use pairwise-priority style weighting and ranking.',
  dematel: 'Model causal influence among factors.',
  vikor: 'Find a compromise solution using utility and regret.',
  copras: 'Evaluate relative significance of alternatives.',
  saw: 'Use additive weighted utility scoring.',
  srp: 'Rank alternatives from weighted criterion-wise rank positions.',
  fuca: 'Rank alternatives by weighted criterion-wise ranks without normalization.',
  seca: 'Simultaneously derive objective criteria weights and alternative scores.',
  dear: 'Rank alternatives with data-envelopment-style response desirability weights.',
  eamr: 'Rank alternatives with blended normalization and benefit-cost appraisal.',
  rawec: 'Rank alternatives with double normalization and weighted deviation index.',
  comet: 'Rank alternatives by fuzzy characteristic-object interpolation.',
  wpm: 'Use multiplicative weighted utility scoring.',
  waspas: 'Blend additive and product utility models.',
  moora: 'Rank by multi-objective ratio analysis.',
  moosra: 'Rank by the ratio of weighted benefit and cost objective sums.',
  arlon: 'Rank alternatives using two-step logarithmic normalization.',
  macont: 'Rank alternatives through comprehensive normalization and mixed aggregation.',
  aras: 'Rank alternatives by additive ratio utility.',
  edas: 'Evaluate distance from average solution.',
  mabac: 'Rank by distance from border approximation area.',
  codas: 'Rank by combinative distance from negative ideal solution.',
  cocoso: 'Combine sum, power, and compromise appraisal scores.',
  cradis: 'Rank by deviations from ideal and anti-ideal solutions.',
  mara: 'Rank by the magnitude of area gap from an optimal alternative.',
  raps: 'Rank alternatives by perimeter similarity to an optimal alternative.',
  oreste: 'Rank alternatives from criterion and within-criterion preference ranks.',
  qualiflex: 'Find a ranking order by maximizing weighted concordance across permutations.',
  regime: 'Rank alternatives by weighted pairwise dominance relations.',
  evamix: 'Rank mixed-data decisions through pairwise dominance appraisal.',
  lexicographic: 'Rank alternatives by strict criterion priority without trade-offs.',
  marcos: 'Rank alternatives relative to ideal and anti-ideal solutions.',
  mairca: 'Rank by gaps between theoretical and real assessments.',
  promethee: 'Rank alternatives by positive and negative preference flows.',
  electre: 'Use concordance and discordance outranking relations.',
  smart: 'Use normalized weighted utility scoring.',
  maut: 'Aggregate single-attribute utilities into total utility.',
  smarter: 'Use rank-order centroid weights with additive utility scoring.',
  macbeth: 'Map qualitative attractiveness categories to additive value scores.',
  pugh: 'Compare alternatives against a selected baseline concept.',
  ocra: 'Rank by operational competitiveness ratings.',
  multimoora: 'Combine ratio, reference point, and multiplicative MOORA rankings.',
  psi: 'Rank alternatives using preference selection index weights.',
  piv: 'Rank by proximity index values from weighted normalized data.',
  rov: 'Rank by average best and worst utility values.',
  wisp: 'Integrate weighted sum and product appraisal components.',
  todim: 'Rank alternatives through prospect-theory dominance.',
  ram: 'Rank by root assessment utility across benefit and cost criteria.',
  gra: 'Rank by grey relational coefficients and relational grade.',
  grp: 'Rank by grey relational projection toward positive and negative ideals.',
  spotis: 'Rank by weighted distance from a stable ideal solution.',
  espSpotis: 'Rank by weighted distance from a researcher-defined expected solution point.',
  balancedSpotis: 'Balance distance from ideal and expected solution points.',
  wedba: 'Rank by weighted Euclidean distance to ideal and anti-ideal points.',
  lmaw: 'Rank by logarithmic additive weighting of standardized criteria.',
  dnma: 'Rank by double normalization and multiple aggregation models.',
  probid: 'Rank by ideal and average weighted-distance preferences.',
  sprobid: 'Rank by simplified first/last-quarter ideal-distance preferences.',
  rim: 'Rank by closeness to a reference ideal interval.',
  rafsi: 'Rank by functional mapping into a common decision interval.',
  lopm: 'Rank alternatives against lower, upper, and target property limits.',
  aroman: 'Rank by aggregated ratio analysis using blended normalization.',
  cobra: 'Rank by comprehensive distance from ideal, anti-ideal, and average solutions.',
  ervd: 'Rank by relative value distances from a decision-maker reference point.',
};

export const methodFamilies = {
  all: 'All methods',
  utility: 'Utility/additive',
  distance: 'Distance/reference',
  compromise: 'Compromise/rank aggregation',
  ratio: 'Ratio/proportional',
  outranking: 'Outranking',
  causal: 'Cause-effect',
  pairwise: 'Pairwise/priority',
  grey: 'Grey/relational',
  newer: 'Newer ranking',
} as const;

export type MethodFamily = keyof typeof methodFamilies;

export const methodFamilyById: Record<MethodId, Exclude<MethodFamily, 'all'>> = {
  topsis: 'distance',
  ahp: 'pairwise',
  dematel: 'causal',
  vikor: 'compromise',
  copras: 'ratio',
  saw: 'utility',
  srp: 'newer',
  fuca: 'newer',
  seca: 'newer',
  dear: 'newer',
  eamr: 'newer',
  rawec: 'newer',
  comet: 'newer',
  wpm: 'utility',
  waspas: 'utility',
  moora: 'ratio',
  moosra: 'ratio',
  arlon: 'newer',
  macont: 'newer',
  aras: 'ratio',
  edas: 'distance',
  mabac: 'distance',
  codas: 'distance',
  cocoso: 'compromise',
  cradis: 'distance',
  mara: 'newer',
  raps: 'newer',
  oreste: 'compromise',
  qualiflex: 'compromise',
  regime: 'compromise',
  evamix: 'compromise',
  lexicographic: 'compromise',
  marcos: 'ratio',
  mairca: 'ratio',
  promethee: 'outranking',
  electre: 'outranking',
  smart: 'utility',
  maut: 'utility',
  smarter: 'utility',
  macbeth: 'utility',
  pugh: 'utility',
  ocra: 'newer',
  multimoora: 'compromise',
  psi: 'newer',
  piv: 'distance',
  rov: 'utility',
  wisp: 'utility',
  todim: 'newer',
  ram: 'utility',
  gra: 'grey',
  grp: 'grey',
  spotis: 'distance',
  espSpotis: 'distance',
  balancedSpotis: 'distance',
  wedba: 'distance',
  lmaw: 'utility',
  dnma: 'compromise',
  probid: 'distance',
  sprobid: 'distance',
  rim: 'distance',
  rafsi: 'newer',
  lopm: 'distance',
  aroman: 'utility',
  cobra: 'distance',
  ervd: 'distance',
};
